# Generated by Django 5.1.5 on 2025-02-08 08:22

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد رشته')),
                ('capacity', models.SmallIntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='website_maj_code_d1a34f_idx')],
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=website.models.student.image_saving_location, verbose_name='عکس')),
                ('marriage', models.BooleanField(default=False, verbose_name='وضعیت تاهل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت')),
                ('entrance_year', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='سال ورودی')),
                ('last_year', models.SmallIntegerField(blank=True, null=True, verbose_name='آخرین سال تحصیل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد دانشگاه')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='website_uni_code_47596c_idx')],
            },
        ),
    ]
