# Generated by Django 5.1.5 on 2025-05-05 17:10

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('code', models.PositiveSmallIntegerField(default=0, verbose_name='کد گروه')),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد رشته')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='website_maj_code_d1a34f_idx')],
            },
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='کد درس')),
                ('unit', models.PositiveSmallIntegerField(verbose_name='تعداد واحد')),
                ('unit_type', models.CharField(choices=[('نظری', 'نظری'), ('نظری-عملی', 'نظری - عملی'), ('عملی', 'عملی'), ('آز', 'آزمایشگاهی'), ('کارآموزی', 'کارآموزی')], default='نظری', max_length=11, verbose_name='نوع واحد')),
                ('lesson_type', models.CharField(choices=[('اصلی', 'اصلی'), ('پایه', 'پایه'), ('عمومی', 'عمومی'), ('تخصصی', 'تخصصی'), ('اختیاری', 'اختیاری')], default='اصلی', max_length=9, verbose_name='نوع درس')),
                ('hamniaz', models.ManyToManyField(blank=True, to='website.lesson', verbose_name='هم نیاز')),
                ('pishniaz', models.ManyToManyField(blank=True, to='website.lesson', verbose_name='پیش نیاز')),
                ('lesson_major', models.ManyToManyField(to='website.major', verbose_name='رشته')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('first_name', models.CharField(max_length=70, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('professor_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=website.models.professor.image_saving_location, verbose_name='عکس')),
                ('professor_major', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره موبایل')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('professor_code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='کد استاد')),
                ('role', models.CharField(default='professor', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lesson_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه')], default='شنبه', max_length=10, verbose_name='روز برگزاری کلاس')),
                ('lesson_time', models.CharField(max_length=100, verbose_name='ساعت برگزاری')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('class_code', models.PositiveSmallIntegerField(verbose_name='کد ارائه')),
                ('class_number', models.PositiveSmallIntegerField(verbose_name='شماره کلاس')),
                ('semester', models.PositiveSmallIntegerField(blank=True, verbose_name='نیمسال')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='website.group', verbose_name='نام گروه')),
                ('lesson_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='website.lesson', verbose_name='نام درس')),
                ('professor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='website.professor', verbose_name='نام استاد')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=website.models.student.image_saving_location, verbose_name='عکس')),
                ('marriage', models.BooleanField(default=False, verbose_name='وضعیت تاهل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('student_number', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی')),
                ('entrance_year', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='سال ورودی')),
                ('last_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='آخرین سال تحصیل')),
                ('role', models.CharField(default='student', max_length=10)),
                ('status', models.CharField(choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5, verbose_name='وضعیت تحصیل')),
                ('major', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.major', verbose_name='رشته')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='نمره')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade', to='website.lesson_class', verbose_name='درس')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade', to='website.student', verbose_name='دانجشو')),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد دانشگاه')),
                ('address', models.TextField(default='تهران', verbose_name='آدرس')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='website_uni_code_47596c_idx')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.university', verbose_name='دانشگاه'),
        ),
        migrations.AddField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(related_name='professor', to='website.university', verbose_name='دانشگاه(های) مشغول به تحصیل'),
        ),
        migrations.AddField(
            model_name='lesson_class',
            name='university_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='website.university', verbose_name='مکان برگزاری'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['code'], name='website_les_code_4c271c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number', 'student_id'], name='website_stu_student_68c314_idx'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['professor_code', 'professor_id'], name='website_pro_profess_dc4420_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson_class',
            constraint=models.UniqueConstraint(fields=('class_code', 'semester'), name='unique_ClassCode_semester'),
        ),
    ]
