# Generated by Django 5.1.5 on 2025-02-17 14:51

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='کد درس')),
                ('unit', models.SmallIntegerField(verbose_name='تعداد واحد')),
                ('unit_type', models.CharField(choices=[('نظری', 'نظری'), ('نظری-عملی', 'نظری - عملی'), ('عملی', 'عملی'), ('آز', 'آزمایشگاهی'), ('کارآموزی', 'کارآموزی')], default='نظری', max_length=11, verbose_name='نوع واحد')),
                ('lesson_type', models.CharField(choices=[('اصلی', 'اصلی'), ('پایه', 'پایه'), ('عمومی', 'عمومی'), ('تخصصی', 'تخصصی'), ('اختیاری', 'اختیاری')], default='اصلی', max_length=9, verbose_name='نوع درس')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('first_name', models.CharField(max_length=70, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('professor_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=website.models.professor.image_saving_location, verbose_name='عکس')),
                ('professor_major', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره موبایل')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('professor_code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='کد استاد')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.major', verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='student',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.university', verbose_name='دانشگاه'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='website_stu_student_8f3999_idx'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hamniaz',
            field=models.ManyToManyField(blank=True, to='website.lesson', verbose_name='هم نیاز'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_major',
            field=models.ManyToManyField(to='website.major', verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pishniaz',
            field=models.ManyToManyField(blank=True, to='website.lesson', verbose_name='پیش نیاز'),
        ),
        migrations.AddField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(related_name='professor', to='website.university', verbose_name='دانشگاه(های) مشغول به تحصیل'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['professor_code'], name='website_pro_profess_9795b2_idx'),
        ),
    ]
