# Generated by Django 5.1.5 on 2025-05-05 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='professor',
            name='website_pro_profess_dc4420_idx',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='professor_code',
            new_name='code',
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['code', 'professor_id'], name='website_pro_code_ec4ae1_idx'),
        ),
    ]
