# Generated by Django 5.1.5 on 2025-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_lesson_professor_remove_student_id_student_major_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['code'], name='website_les_code_4c271c_idx'),
        ),
    ]
