# Generated by Django 5.1.5 on 2025-02-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_major_student_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='major', to='website.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unversity', to='website.university', verbose_name='دانشگاه'),
        ),
    ]
