# Generated by Django 5.1.5 on 2025-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lesson_class_degree_lesson_class_degree_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='lesson_day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یک شنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه')], default='شنبه', max_length=10, verbose_name='روز برگزاری کلاس'),
        ),
    ]
