# Generated by Django 5.1.5 on 2025-03-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lesson_website_les_code_4c271c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField(verbose_name='نیم سال تحصیلی')),
                ('lesson_name', models.ManyToManyField(related_name='student', to='website.lesson', verbose_name='دروس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='website.student', verbose_name='دانشجو')),
            ],
        ),
    ]
