# Generated by Django 5.1.5 on 2025-05-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_lesson_class_lesson_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_choosing_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField(default=0, verbose_name='نیمسال')),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(related_name='professor', to='website.university', verbose_name='دانشگاه(های) مشغول به تدریس'),
        ),
        migrations.AddIndex(
            model_name='lesson_class',
            index=models.Index(fields=['class_code', 'semester'], name='website_les_class_c_ba2b34_idx'),
        ),
        migrations.AddField(
            model_name='student_choosing_lesson',
            name='chosen_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='website.lesson_class', verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='student_choosing_lesson',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='website.student', verbose_name='دانشجو'),
        ),
    ]
