# Generated by Django 5.1.5 on 2025-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_student_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_lessons',
            name='semester',
            field=models.SmallIntegerField(blank=True, verbose_name='نیم سال تحصیلی'),
        ),
    ]
