# Generated by Django 5.1.5 on 2025-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_student_id_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False),
        ),
    ]
