# Generated by Django 5.1.5 on 2025-02-10 16:57

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_student_student_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='website.university', verbose_name='دانشگاه'),
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('first_name', models.CharField(max_length=70, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('professor_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=website.models.professor.image_saving_location, verbose_name='عکس')),
                ('professor_major', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره موبایل')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('professor_code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='کد استاد')),
                ('universities', models.ManyToManyField(related_name='professor', to='website.university', verbose_name='دانشگاه(های) مشغول به تحصیل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['professor_code'], name='website_pro_profess_9795b2_idx')],
            },
        ),
    ]
