# Generated by Django 5.1.5 on 2025-03-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_student_lessons_created_student_lessons_modified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_lessons',
        ),
    ]
