# Generated by Django 5.1.5 on 2025-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_student_major_alter_student_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی'),
        ),
    ]
