# Generated by Django 5.1.5 on 2025-06-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_student_choosing_lesson_chosen_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_choosing_lesson',
            name='chosen_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='website.lesson_class', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='student_choosing_lesson',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='website.student', verbose_name='دانشجو'),
        ),
    ]
