# Generated by Django 5.1.5 on 2025-02-11 13:48

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی'),
        ),
    ]
