# Generated by Django 5.1.5 on 2025-03-18 13:36

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_group_lesson_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddConstraint(
            model_name='lesson_class',
            constraint=models.UniqueConstraint(fields=('class_code', 'semester'), name='unique_ClassCode_semester'),
        ),
    ]
