# Generated by Django 5.1.5 on 2025-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_student_choosing_lesson_chosen_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='نمره'),
        ),
    ]
