# Generated by Django 5.1.4 on 2025-07-15 12:00

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_grade_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_choosing_lesson',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ انتخاب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_choosing_lesson',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='website.lesson_class', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='website.student', verbose_name='دانشجو'),
        ),
    ]
