# Generated by Django 5.1.5 on 2025-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_lesson_class_created_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson_class',
            name='unique_ClassCode_semester',
        ),
        migrations.AddConstraint(
            model_name='lesson_class',
            constraint=models.UniqueConstraint(fields=('class_code', 'semester'), name='unique_ClassCode_semester', violation_error_message='یک کلاس با کدارائه داده شده در نیمسال داده شده وجود دارد'),
        ),
    ]
