# Generated by Django 5.1.5 on 2025-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_lesson_class_unique_classcode_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson_class',
            name='unique_ClassCode_semester',
        ),
        migrations.AddConstraint(
            model_name='lesson_class',
            constraint=models.UniqueConstraint(fields=('class_code', 'semester'), name='unique_ClassCode_semester'),
        ),
    ]
