# Generated by Django 5.1.5 on 2025-03-23 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_lesson_class_unique_classcode_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='professor',
            name='website_pro_profess_9795b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='website_stu_student_8f3999_idx',
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='semester',
            field=models.SmallIntegerField(blank=True, verbose_name='نیمسال'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['professor_code', 'professor_id'], name='website_pro_profess_dc4420_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number', 'student_id'], name='website_stu_student_68c314_idx'),
        ),
    ]
