# Generated by Django 5.1.5 on 2025-03-25 09:00

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_professor_website_pro_profess_9795b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(verbose_name='نمره')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade', to='website.lesson_class', verbose_name='درس')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade', to='website.student', verbose_name='دانجشو')),
            ],
        ),
    ]
