# Generated by Django 5.1.5 on 2025-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='role',
            field=models.CharField(default='professor', max_length=7),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=7),
        ),
    ]
