# Generated by Django 5.1.5 on 2025-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_professor_role_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5, verbose_name='وضعیت تحصیل'),
        ),
    ]
