# Generated by Django 5.0.7 on 2024-07-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='passwords',
            new_name='password',
        ),
    ]
