# Generated by Django 5.0.7 on 2024-07-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_passwords_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('engine_type', models.CharField(choices=[('V', 'V type'), ('i', 'inline'), ('F', 'Flat'), ('B', 'Boxer'), ('W', 'W type'), ('R', 'Rotary')], default='i', max_length=2)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('AC', 'Accept'), ('RJ', 'Rejected')], default='DR', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.signup')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['author'], name='blog_post_author__038a48_idx')],
            },
        ),
    ]
