# Generated by Django 5.0.7 on 2024-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status_date',
            field=models.DateTimeField(default=None),
        ),
    ]
