# Generated by Django 5.0.7 on 2024-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
