# Generated by Django 5.0.7 on 2024-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('FE', 'Female'), ('MA', 'Male'), ('CR', 'Corrosan')], default='MA', max_length=2),
        ),
    ]
