# Generated by Django 5.0.7 on 2024-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('RJ', 'Rejected'), ('AC', 'Accepted')], default='DR', max_length=2),
        ),
    ]
