# Generated by Django 5.0.7 on 2024-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('FE', 'Female'), ('M', 'Male'), ('CR', 'Corrosan')], default='M', max_length=2),
        ),
    ]
