# Generated by Django 5.0.7 on 2024-11-02 09:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=None, size=[500, 500], upload_to='post_images/'),
        ),
    ]
