# Generated by Django 5.0.7 on 2024-11-16 07:43

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=None, size=[500, 500], upload_to='post_images/2024-11-16 11:13:42.720793/<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x000001B2A2452360>'),
        ),
    ]
