# Generated by Django 5.0.7 on 2024-11-16 07:58

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=None, size=[500, 500], upload_to='post_images/2024-11-16 11:28:59.128487/'),
        ),
    ]
