# Generated by Django 5.0.7 on 2024-11-16 08:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=None, size=[500, 500], upload_to='post_images/2024-11-16 11:44:57.442600/11'),
        ),
    ]
