# Generated by Django 5.0.7 on 2024-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_title_12aef5_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['date_created'], name='blog_image_date_cr_9f5874_idx'),
        ),
    ]
