# Generated by Django 5.0.7 on 2024-12-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
    ]
